#!/usr/bin/env node
/*
 * Generate the registration QR code shown on event scenes.
 *
 *   node scripts/generate-qr.mjs
 *
 * Reads `registration.url` from content/settings.json and writes
 * web/img/register-qr.svg, with the VHF seal composited into the centre.
 *
 * Why generate rather than hand off an image file: the payload is then correct
 * by construction. A QR code is unreadable to a human, so a wrong or stale one
 * looks exactly like a right one until a veteran scans it and lands nowhere.
 * tests/qr.test.mjs fails if this file and settings.json ever disagree.
 *
 * The output is committed rather than built on the fly, the same as the app
 * icons: the display must work offline and CLAUDE.md caps it at two hosts, so
 * nothing here may reach for a QR service or a runtime library. Re-run this
 * after changing the URL.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import QRCode from "qrcode";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SETTINGS = path.join(ROOT, "content", "settings.json");
// The 128px derivative, not the 1024px original: the seal renders at roughly
// 57 device pixels inside the code, and embedding the full-size logo made the
// SVG 78 KB of base64 for no visible gain.
const LOGO = path.join(ROOT, "content", "artwork", "brand", "vhf-logo-128.png");
const OUT = path.join(ROOT, "web", "img", "register-qr.svg");

/*
 * Level H tolerates ~30% of the code being obscured, which is what buys room
 * for the seal in the middle. Do not lower this while a logo is overlaid.
 */
const ERROR_CORRECTION = "H";

/* Fraction of the code's width covered by the logo plate. 0.22 stays well
 * inside what level H can reconstruct; pushing past ~0.3 starts costing scans. */
const LOGO_FRACTION = 0.22;

async function main() {
  const settings = JSON.parse(await fs.readFile(SETTINGS, "utf8"));
  const url = settings.registration && settings.registration.url;
  if (!url) throw new Error('content/settings.json: "registration.url" is missing');

  const svg = await QRCode.toString(url, {
    type: "svg",
    errorCorrectionLevel: ERROR_CORRECTION,
    margin: 2,
    // The light field is transparent here and supplied by the scene instead
    // (.scene__qr in web/css/scene.css), so the code sits on a designed cream
    // card rather than a hard white square. It is still a light field -- a QR
    // over the event scene's dark fade would not scan at all.
    color: { dark: "#12210f", light: "#0000" }
  });

  // qrcode emits `viewBox="0 0 N N"`; every coordinate below is in those units.
  const viewBox = /viewBox="0 0 (\d+(?:\.\d+)?) /.exec(svg);
  if (!viewBox) throw new Error("could not read the viewBox from the generated SVG");
  const size = Number(viewBox[1]);

  const logo = await fs.readFile(LOGO);
  const plate = size * LOGO_FRACTION;
  const mark = plate * 0.84; // a little white breathing room inside the plate
  const plateXY = (size - plate) / 2;
  const markXY = (size - mark) / 2;

  // The plate behind the seal stays opaque: it is what the error correction is
  // "spending" its 30% headroom on, and a translucent one would let the photo
  // through and break the contrast the decoder needs.
  const overlay =
    `<rect x="${plateXY.toFixed(3)}" y="${plateXY.toFixed(3)}" ` +
    `width="${plate.toFixed(3)}" height="${plate.toFixed(3)}" rx="${(plate * 0.16).toFixed(3)}" fill="#f6f3ea"/>` +
    `<image x="${markXY.toFixed(3)}" y="${markXY.toFixed(3)}" ` +
    `width="${mark.toFixed(3)}" height="${mark.toFixed(3)}" ` +
    `preserveAspectRatio="xMidYMid meet" ` +
    `href="data:image/png;base64,${logo.toString("base64")}"/>`;

  // The URL in a comment is what the drift test reads: decoding the modules
  // back out would be a lot of machinery to answer a question the generator
  // already knows the answer to.
  const annotated = svg
    .replace(/^<\?xml[^>]*\?>\s*/, "")
    .replace("<svg ", `<!-- generated by scripts/generate-qr.mjs -->\n<!-- encodes: ${url} -->\n<svg `)
    .replace("</svg>", `${overlay}</svg>`);

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, annotated.trimEnd() + "\n", "utf8");

  console.log(`[qr] ${url}`);
  console.log(`[qr] level ${ERROR_CORRECTION}, ${size}x${size} units -> ${path.relative(ROOT, OUT)}`);
}

main().catch((err) => {
  console.error("[qr] failed:", err.message);
  process.exitCode = 1;
});
